#ifndef MESSNUM_BOARD_BATTLE_H
#define MESSNUM_BOARD_BATTLE_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_BATTLE_START = MESSNUM(MESS_BOARD_BATTLE, 0),
    MESS_BOARD_BATTLE_COINNUM = MESSNUM(MESS_BOARD_BATTLE, 1),
    MESS_BOARD_BATTLE_COINNUM_LOW = MESSNUM(MESS_BOARD_BATTLE, 2),
    MESS_BOARD_BATTLE_MGSTART = MESSNUM(MESS_BOARD_BATTLE, 3),
    MESS_BOARD_BATTLE_SELECT_HELP = MESSNUM(MESS_BOARD_BATTLE, 4),
};

#endif