#ifndef MESSNUM_BOARDSTAR_H
#define MESSNUM_BOARDSTAR_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_STORY_LOSE_0 = MESSNUM(MESS_BOARD_STORY, 0),
    MESS_BOARD_STORY_LOSE_1 = MESSNUM(MESS_BOARD_STORY, 1),
    MESS_BOARD_STORY_LOSE_2 = MESSNUM(MESS_BOARD_STORY, 2),
    MESS_BOARD_STORY_LOSE_3 = MESSNUM(MESS_BOARD_STORY, 3),
    MESS_BOARD_STORY_LOSE_4 = MESSNUM(MESS_BOARD_STORY, 4),
    MESS_BOARD_STORY_SCENE0 = MESSNUM(MESS_BOARD_STORY, 5),
    MESS_BOARD_STORY_SCENE1 = MESSNUM(MESS_BOARD_STORY, 31),
    MESS_BOARD_STORY_SCENE2 = MESSNUM(MESS_BOARD_STORY, 55),
    MESS_BOARD_STORY_SCENE3 = MESSNUM(MESS_BOARD_STORY, 89),
    MESS_BOARD_STORY_SCENE4 = MESSNUM(MESS_BOARD_STORY, 115),
    MESS_BOARD_STORY_EXIT_PLAYER = MESSNUM(MESS_BOARD_STORY, 139),
    MESS_BOARD_STORY_EXIT_GRUMBLE = MESSNUM(MESS_BOARD_STORY, 140),
    MESS_BOARD_STORY_LOSE = MESSNUM(MESS_BOARD_STORY, 141),
    MESS_BOARD_STORY_GAME_OVER = MESSNUM(MESS_BOARD_STORY, 142),
    MESS_BOARD_STORY_TIE = MESSNUM(MESS_BOARD_STORY, 143),
    MESS_BOARD_STORY_TIE_USELESS = MESSNUM(MESS_BOARD_STORY, 144),
    MESS_BOARD_STORY_TIE_COIN = MESSNUM(MESS_BOARD_STORY, 145),
    MESS_BOARD_STORY_TIE_DREAM = MESSNUM(MESS_BOARD_STORY, 146),
};

#endif