#ifndef MESSNUM_BOARDSTAR_H
#define MESSNUM_BOARDSTAR_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_STAR_CHORL_1 = MESSNUM(MESS_BOARD_STAR, 0),
    MESS_BOARD_STAR_CHORL_2 = MESSNUM(MESS_BOARD_STAR, 1),
    MESS_BOARD_STAR_CHORL_3  = MESSNUM(MESS_BOARD_STAR, 2),
    MESS_BOARD_STAR_CHORL_4  = MESSNUM(MESS_BOARD_STAR, 3),
    MESS_BOARD_STAR_CHORL_5  = MESSNUM(MESS_BOARD_STAR, 4),
    MESS_BOARD_STAR_CHORL_6  = MESSNUM(MESS_BOARD_STAR, 5),
    MESS_BOARD_STAR_NEXT_1  = MESSNUM(MESS_BOARD_STAR, 6),
    MESS_BOARD_STAR_NEXT_2  = MESSNUM(MESS_BOARD_STAR, 7),
    MESS_BOARD_STAR_FIRST_1  = MESSNUM(MESS_BOARD_STAR, 8),
    MESS_BOARD_STAR_FIRST_2  = MESSNUM(MESS_BOARD_STAR, 9),
};

#endif