#ifndef MESSNUM_BOARDPAUSE_H
#define MESSNUM_BOARDPAUSE_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_PAUSE_PAD_CHANGE = MESSNUM(MESS_BOARD_PAUSE, 0),
    MESS_BOARD_PAUSE_PAD_SELECT = MESSNUM(MESS_BOARD_PAUSE, 1),
    MESS_BOARD_PAUSE_PLAYER_CONFIG = MESSNUM(MESS_BOARD_PAUSE, 2),
    MESS_BOARD_PAUSE_PLAYER_TYPE_MAN = MESSNUM(MESS_BOARD_PAUSE, 3),
    MESS_BOARD_PAUSE_PLAYER_TYPE_COM = MESSNUM(MESS_BOARD_PAUSE, 4),
    MESS_BOARD_PAUSE_MGINST_ON = MESSNUM(MESS_BOARD_PAUSE, 5),
    MESS_BOARD_PAUSE_MGINST_OFF = MESSNUM(MESS_BOARD_PAUSE, 6),
    MESS_BOARD_PAUSE_MGCOM_ON = MESSNUM(MESS_BOARD_PAUSE, 7),
    MESS_BOARD_PAUSE_MGCOM_OFF = MESSNUM(MESS_BOARD_PAUSE, 8),
    MESS_BOARD_PAUSE_MGPACK_ALL = MESSNUM(MESS_BOARD_PAUSE, 9),
    MESS_BOARD_PAUSE_MGPACK_EASY = MESSNUM(MESS_BOARD_PAUSE, 10),
    MESS_BOARD_PAUSE_MGPACK_ACTION = MESSNUM(MESS_BOARD_PAUSE, 11),
    MESS_BOARD_PAUSE_MGPACK_SKILL = MESSNUM(MESS_BOARD_PAUSE, 12),
    MESS_BOARD_PAUSE_RUMBLE_ON = MESSNUM(MESS_BOARD_PAUSE, 13),
    MESS_BOARD_PAUSE_RUMBLE_OFF = MESSNUM(MESS_BOARD_PAUSE, 14),
    MESS_BOARD_PAUSE_MESS_SPEED_FAST = MESSNUM(MESS_BOARD_PAUSE, 15),
    MESS_BOARD_PAUSE_MESS_SPEED_MID = MESSNUM(MESS_BOARD_PAUSE, 16),
    MESS_BOARD_PAUSE_MESS_SPEED_SLOW = MESSNUM(MESS_BOARD_PAUSE, 17),
    MESS_BOARD_PAUSE_SAVE_ALWAYS = MESSNUM(MESS_BOARD_PAUSE, 18),
    MESS_BOARD_PAUSE_SAVE_ONCE = MESSNUM(MESS_BOARD_PAUSE, 19),
    MESS_BOARD_PAUSE_SAVE_NEVER = MESSNUM(MESS_BOARD_PAUSE, 20),
    MESS_BOARD_PAUSE_MES_QUIT = MESSNUM(MESS_BOARD_PAUSE, 21),
    MESS_BOARD_PAUSE_MES_QUIT_CONFIRM = MESSNUM(MESS_BOARD_PAUSE, 22),
    MESS_BOARD_PAUSE_PAD_OPTION = MESSNUM(MESS_BOARD_PAUSE, 23),
    MESS_BOARD_PAUSE_PAD_QUIT = MESSNUM(MESS_BOARD_PAUSE, 24),
    MESS_BOARD_PAUSE_MGPACK_GOOFY = MESSNUM(MESS_BOARD_PAUSE, 25),
    MESS_BOARD_PAUSE_PAD_MGCIRCUIT = MESSNUM(MESS_BOARD_PAUSE, 26),
};

#endif