#ifndef MESSNUM_BOARD_W06_H
#define MESSNUM_BOARD_W06_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_W06_CAKETHROW_ENTER = MESSNUM(MESS_BOARD_W06, 0),
    MESS_BOARD_W06_CAKETHROW_INST = MESSNUM(MESS_BOARD_W06, 1),
    MESS_BOARD_W06_CAKETHROW_RESULT = MESSNUM(MESS_BOARD_W06, 2),
    MESS_BOARD_W06_CAKETHROW_FAIL = MESSNUM(MESS_BOARD_W06, 3),
    MESS_BOARD_W06_KANE_BEGIN = MESSNUM(MESS_BOARD_W06, 4),
    MESS_BOARD_W06_KANE_PARTY = MESSNUM(MESS_BOARD_W06, 5),
    MESS_BOARD_W06_KANE_ROULETTE = MESSNUM(MESS_BOARD_W06, 6),
    MESS_BOARD_W06_KANE_ROULETTE_RESULT = MESSNUM(MESS_BOARD_W06, 7),
    MESS_BOARD_W06_KANE_END = MESSNUM(MESS_BOARD_W06, 8),
    MESS_BOARD_W06_KANE_5COIN = MESSNUM(MESS_BOARD_W06, 9),
    MESS_BOARD_W06_KANE_CAP_FAIL = MESSNUM(MESS_BOARD_W06, 10),
    MESS_BOARD_W06_KANE_CAP_FULL = MESSNUM(MESS_BOARD_W06, 11),
    MESS_BOARD_W06_KANE_CAP_FULL2 = MESSNUM(MESS_BOARD_W06, 12),
    MESS_BOARD_W06_KANE_STAR_FAIL = MESSNUM(MESS_BOARD_W06, 13),
    MESS_BOARD_W06_KANE_RESULT_COIN = MESSNUM(MESS_BOARD_W06, 14),
    MESS_BOARD_W06_KANE_RESULT_STAR = MESSNUM(MESS_BOARD_W06, 15),
    MESS_BOARD_W06_KANE_RESULT_CAPSULE = MESSNUM(MESS_BOARD_W06, 16),
};

#endif