#ifndef MESSNUM_BOARD_W05_H
#define MESSNUM_BOARD_W05_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_W05_ROCKET_START = MESSNUM(MESS_BOARD_W05, 0),
    MESS_BOARD_W05_ROCKET_END = MESSNUM(MESS_BOARD_W05, 1),
    MESS_BOARD_W05_TAXI_START = MESSNUM(MESS_BOARD_W05, 2),
    MESS_BOARD_W05_TAXI_COIN = MESSNUM(MESS_BOARD_W05, 3),
    MESS_BOARD_W05_TAXI_COIN_EMPTY = MESSNUM(MESS_BOARD_W05, 4),
    MESS_BOARD_W05_TAXI_COIN_LOW = MESSNUM(MESS_BOARD_W05, 5),
    MESS_BOARD_W05_WARP_CHOICE = MESSNUM(MESS_BOARD_W05, 6),
    MESS_BOARD_W05_RJET_CHOICE = MESSNUM(MESS_BOARD_W05, 7),
    MESS_BOARD_W05_RJET_INST = MESSNUM(MESS_BOARD_W05, 8),
    MESS_BOARD_W05_RJET_END = MESSNUM(MESS_BOARD_W05, 9),
    MESS_BOARD_W05_RJET_HELP = MESSNUM(MESS_BOARD_W05, 10),
    MESS_BOARD_W05_REEL_START = MESSNUM(MESS_BOARD_W05, 11),
    MESS_BOARD_W05_REEL_INST = MESSNUM(MESS_BOARD_W05, 12),
    MESS_BOARD_W05_REEL_INST_BTN = MESSNUM(MESS_BOARD_W05, 13),
    MESS_BOARD_W05_REEL_HELP = MESSNUM(MESS_BOARD_W05, 14),
    MESS_BOARD_W05_REEL_CAP_FULL = MESSNUM(MESS_BOARD_W05, 15),
    MESS_BOARD_W05_REEL_KINOKO = MESSNUM(MESS_BOARD_W05, 16),
};

#endif