#ifndef MESSNUM_BOARDGATE_H
#define MESSNUM_BOARDGATE_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_GATE_BATTAN_CHOICE = MESSNUM(MESS_BOARD_GATE, 0),
    MESS_BOARD_GATE_BATTAN_YES = MESSNUM(MESS_BOARD_GATE, 1),
    MESS_BOARD_GATE_BATTAN_NO = MESSNUM(MESS_BOARD_GATE, 2),
    MESS_BOARD_GATE_BATTAN_COIN = MESSNUM(MESS_BOARD_GATE, 3),
    MESS_BOARD_GATE_DOSSUN_CHOICE_UP = MESSNUM(MESS_BOARD_GATE, 4),
    MESS_BOARD_GATE_DOSSUN_CHOICE_DOWN = MESSNUM(MESS_BOARD_GATE, 5),
    MESS_BOARD_GATE_DOSSUN_YES = MESSNUM(MESS_BOARD_GATE, 6),
    MESS_BOARD_GATE_DOSSUN_NO = MESSNUM(MESS_BOARD_GATE, 7),
    MESS_BOARD_GATE_DOSSUN_COIN = MESSNUM(MESS_BOARD_GATE, 8),
};

#endif