#ifndef MESSNUM_MESS_BOARDOPENING_H
#define MESSNUM_MESS_BOARDOPENING_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_OPENING_BOARD1 = MESSNUM(MESS_BOARD_OPENING, 0),
    MESS_BOARD_OPENING_BOARD2 = MESSNUM(MESS_BOARD_OPENING, 1),
    MESS_BOARD_OPENING_BOARD3 = MESSNUM(MESS_BOARD_OPENING, 2),
    MESS_BOARD_OPENING_BOARD4 = MESSNUM(MESS_BOARD_OPENING, 3),
    MESS_BOARD_OPENING_BOARD5 = MESSNUM(MESS_BOARD_OPENING, 4),
    MESS_BOARD_OPENING_BOARD6 = MESSNUM(MESS_BOARD_OPENING, 5),
    MESS_BOARD_OPENING_BOARD7 = MESSNUM(MESS_BOARD_OPENING, 6),
    MESS_BOARD_OPENING_TURNORDER = MESSNUM(MESS_BOARD_OPENING, 7),
    MESS_BOARD_OPENING_TURNORDER1 = MESSNUM(MESS_BOARD_OPENING, 8),
    MESS_BOARD_OPENING_TURNORDER2 = MESSNUM(MESS_BOARD_OPENING, 9),
    MESS_BOARD_OPENING_TURNORDER3 = MESSNUM(MESS_BOARD_OPENING, 10),
    MESS_BOARD_OPENING_TURNORDER4 = MESSNUM(MESS_BOARD_OPENING, 11),
    MESS_BOARD_OPENING_10COINS = MESSNUM(MESS_BOARD_OPENING, 12),
    MESS_BOARD_OPENING_DONKEYMASU = MESSNUM(MESS_BOARD_OPENING, 13),
    MESS_BOARD_OPENING_DONKEYMASU_DISP = MESSNUM(MESS_BOARD_OPENING, 14),
    MESS_BOARD_OPENING_EVENT = MESSNUM(MESS_BOARD_OPENING, 15),
    
};

#endif