#ifndef MESSNUM_BOARD_MGCIRCUIT_H
#define MESSNUM_BOARD_MGCIRCUIT_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_MGCIRCUIT_RULECHOICE = MESSNUM(MESS_BOARD_MGCIRCUIT, 0),
    MESS_BOARD_MGCIRCUIT_RULE1 = MESSNUM(MESS_BOARD_MGCIRCUIT, 1),
    MESS_BOARD_MGCIRCUIT_RULE2 = MESSNUM(MESS_BOARD_MGCIRCUIT, 2),
    MESS_BOARD_MGCIRCUIT_PLAYER = MESSNUM(MESS_BOARD_MGCIRCUIT, 3),
    MESS_BOARD_MGCIRCUIT_PLAYERNUM = MESSNUM(MESS_BOARD_MGCIRCUIT, 4),
    MESS_BOARD_MGCIRCUIT_CAPSULEBEGIN = MESSNUM(MESS_BOARD_MGCIRCUIT, 5),
    MESS_BOARD_MGCIRCUIT_CAPSULEEND = MESSNUM(MESS_BOARD_MGCIRCUIT, 6),
    MESS_BOARD_MGCIRCUIT_START = MESSNUM(MESS_BOARD_MGCIRCUIT, 7),
    MESS_BOARD_MGCIRCUIT_MGFIRST = MESSNUM(MESS_BOARD_MGCIRCUIT, 8),
    MESS_BOARD_MGCIRCUIT_MGNEXT = MESSNUM(MESS_BOARD_MGCIRCUIT, 9),
    MESS_BOARD_MGCIRCUIT_CAPSULEUSE = MESSNUM(MESS_BOARD_MGCIRCUIT, 10),
    MESS_BOARD_MGCIRCUIT_CAPSULECALLED = MESSNUM(MESS_BOARD_MGCIRCUIT, 11),
    MESS_BOARD_MGCIRCUIT_MGSTART = MESSNUM(MESS_BOARD_MGCIRCUIT, 12),
    MESS_BOARD_MGCIRCUIT_RANKBEGIN = MESSNUM(MESS_BOARD_MGCIRCUIT, 13),
    MESS_BOARD_MGCIRCUIT_RANK = MESSNUM(MESS_BOARD_MGCIRCUIT, 14),
    MESS_BOARD_MGCIRCUIT_RANKLAST = MESSNUM(MESS_BOARD_MGCIRCUIT, 15),
    MESS_BOARD_MGCIRCUIT_RANKNUM = MESSNUM(MESS_BOARD_MGCIRCUIT, 16),
    MESS_BOARD_MGCIRCUIT_WINNER = MESSNUM(MESS_BOARD_MGCIRCUIT, 17),
    MESS_BOARD_MGCIRCUIT_WINNER2 = MESSNUM(MESS_BOARD_MGCIRCUIT, 18),
    MESS_BOARD_MGCIRCUIT_WINNER3 = MESSNUM(MESS_BOARD_MGCIRCUIT, 19),
    MESS_BOARD_MGCIRCUIT_ROLLAGAIN = MESSNUM(MESS_BOARD_MGCIRCUIT, 20),
    MESS_BOARD_MGCIRCUIT_TIE = MESSNUM(MESS_BOARD_MGCIRCUIT, 21),
    MESS_BOARD_MGCIRCUIT_WINNERALL = MESSNUM(MESS_BOARD_MGCIRCUIT, 22),
    MESS_BOARD_MGCIRCUIT_GAMEEND = MESSNUM(MESS_BOARD_MGCIRCUIT, 23),
    MESS_BOARD_MGCIRCUIT_RESULT_WIN1 = MESSNUM(MESS_BOARD_MGCIRCUIT, 24),
    MESS_BOARD_MGCIRCUIT_RESULT_WIN2 = MESSNUM(MESS_BOARD_MGCIRCUIT, 25),
    MESS_BOARD_MGCIRCUIT_RESULT_WIN3 = MESSNUM(MESS_BOARD_MGCIRCUIT, 26),
    MESS_BOARD_MGCIRCUIT_RESULT_WIN4 = MESSNUM(MESS_BOARD_MGCIRCUIT, 27),
    MESS_BOARD_MGCIRCUIT_RESULT_SAIROLL = MESSNUM(MESS_BOARD_MGCIRCUIT, 28),
    MESS_BOARD_MGCIRCUIT_RESULT_FINAL = MESSNUM(MESS_BOARD_MGCIRCUIT, 29),
    MESS_BOARD_MGCIRCUIT_RESULT_FINALNAME = MESSNUM(MESS_BOARD_MGCIRCUIT, 30),
    MESS_BOARD_MGCIRCUIT_RESULT_END = MESSNUM(MESS_BOARD_MGCIRCUIT, 31),
    MESS_BOARD_MGCIRCUIT_REVERSE_END = MESSNUM(MESS_BOARD_MGCIRCUIT, 32),
    MESS_BOARD_MGCIRCUIT_REPLAY = MESSNUM(MESS_BOARD_MGCIRCUIT, 33),
};

#endif