#ifndef MESSNUM_BOARD_W01_H
#define MESSNUM_BOARD_W01_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_W06_TRAIN_CHOICE = MESSNUM(MESS_BOARD_W01, 0),
    MESS_BOARD_W06_TRAIN_INST = MESSNUM(MESS_BOARD_W01, 1),
    MESS_BOARD_W06_TRAIN_END = MESSNUM(MESS_BOARD_W01, 2),
};

#endif