#ifndef MESSNUM_BOARDOPE_H
#define MESSNUM_BOARDOPE_H

#include "messdir_enum.h"

enum {
    BOARDOPE_PAD_SAI_CAPSULE = MESSNUM(MESS_BOARDOPE, 0),
    BOARDOPE_PAD_SAI_MAP = MESSNUM(MESS_BOARDOPE, 1),
    BOARDOPE_PAD_SAI = MESSNUM(MESS_BOARDOPE, 2),
    BOARDOPE_PAD_ENTER_SAI = MESSNUM(MESS_BOARDOPE, 3),
    BOARDOPE_PAD_ENTER = MESSNUM(MESS_BOARDOPE, 4),
    BOARDOPE_PAD_SCROLL_CIRCUIT = MESSNUM(MESS_BOARDOPE, 5),
    BOARDOPE_PAD_SWITCH = MESSNUM(MESS_BOARDOPE, 6),
    BOARDOPE_PAD_ENTER_NOEXIT = MESSNUM(MESS_BOARDOPE, 7),
    BOARDOPE_PAD_PAUSE = MESSNUM(MESS_BOARDOPE, 8),
    BOARDOPE_PAD_PAUSE2 = MESSNUM(MESS_BOARDOPE, 9),
    BOARDOPE_MES_SAI_MATCH = MESSNUM(MESS_BOARDOPE, 10),
    BOARDOPE_PAD_CAPSULE_SEL = MESSNUM(MESS_BOARDOPE, 11),
    BOARDOPE_PAD_SCROLL = MESSNUM(MESS_BOARDOPE, 12),
    BOARDOPE_PAD_NOUSE_SEL = MESSNUM(MESS_BOARDOPE, 13),
    BOARDOPE_PAD_CONT_MAP = MESSNUM(MESS_BOARDOPE, 14),
};

#endif