#ifndef MESSNUM_BOARD_NAME_H
#define MESSNUM_BOARD_NAME_H

#include "messdir_enum.h"

enum {
    MESS_BOARD_NAME_W01 = MESSNUM(MESS_BOARD_NAME, 0),
    MESS_BOARD_NAME_W02,
    MESS_BOARD_NAME_W03,
    MESS_BOARD_NAME_W04,
    MESS_BOARD_NAME_W05,
    MESS_BOARD_NAME_W06,
    MESS_BOARD_NAME_W07
};

#endif