#ifndef MESSNUM_MESS_CAPSULE_EX98
#define MESSNUM_MESS_CAPSULE_EX98

#include "messdir_enum.h"

enum {
    MESS_CAPSULE_EX98_KINOKO = MESSNUM(MESS_CAPSULE_EX98, 0),
    MESS_CAPSULE_EX98_SKINOKO = MESSNUM(MESS_CAPSULE_EX98, 1),
    MESS_CAPSULE_EX98_NKINOKO = MESSNUM(MESS_CAPSULE_EX98, 2),
    MESS_CAPSULE_EX98_DOKAN = MESSNUM(MESS_CAPSULE_EX98, 3),
    MESS_CAPSULE_EX98_JANGO = MESSNUM(MESS_CAPSULE_EX98, 4),
    MESS_CAPSULE_EX98_BOBLE = MESSNUM(MESS_CAPSULE_EX98, 5),
    MESS_CAPSULE_EX98_HANACHAN = MESSNUM(MESS_CAPSULE_EX98, 6),
    MESS_CAPSULE_EX98_HAMMERBRO = MESSNUM(MESS_CAPSULE_EX98, 7),
    MESS_CAPSULE_EX98_COINBLOCK = MESSNUM(MESS_CAPSULE_EX98, 8),
    MESS_CAPSULE_EX98_TOGEZO = MESSNUM(MESS_CAPSULE_EX98, 9),
    MESS_CAPSULE_EX98_PATAPATA = MESSNUM(MESS_CAPSULE_EX98, 10),
    MESS_CAPSULE_EX98_KILLER = MESSNUM(MESS_CAPSULE_EX98, 11),
    MESS_CAPSULE_EX98_KURIBO = MESSNUM(MESS_CAPSULE_EX98, 12),
    MESS_CAPSULE_EX98_BOMHEI = MESSNUM(MESS_CAPSULE_EX98, 13),
    MESS_CAPSULE_EX98_BANK = MESSNUM(MESS_CAPSULE_EX98, 14),
    MESS_CAPSULE_EX98_KAMEKKU = MESSNUM(MESS_CAPSULE_EX98, 15),
    MESS_CAPSULE_EX98_THROWMAN = MESSNUM(MESS_CAPSULE_EX98, 16),
    MESS_CAPSULE_EX98_PAKKUN = MESSNUM(MESS_CAPSULE_EX98, 17),
    MESS_CAPSULE_EX98_KOKAMEKKU = MESSNUM(MESS_CAPSULE_EX98, 18),
    MESS_CAPSULE_EX98_UKKI = MESSNUM(MESS_CAPSULE_EX98, 19),
    MESS_CAPSULE_EX98_JUGEM = MESSNUM(MESS_CAPSULE_EX98, 20),
    MESS_CAPSULE_EX98_TUMUJIKUN = MESSNUM(MESS_CAPSULE_EX98, 21),
    MESS_CAPSULE_EX98_KETTOU = MESSNUM(MESS_CAPSULE_EX98, 22),
    MESS_CAPSULE_EX98_WANWAN = MESSNUM(MESS_CAPSULE_EX98, 23),
    MESS_CAPSULE_EX98_HONE = MESSNUM(MESS_CAPSULE_EX98, 24),
    MESS_CAPSULE_EX98_KOOPA = MESSNUM(MESS_CAPSULE_EX98, 25),
    MESS_CAPSULE_EX98_CHANCE = MESSNUM(MESS_CAPSULE_EX98, 26),
    MESS_CAPSULE_EX98_MIRACLE = MESSNUM(MESS_CAPSULE_EX98, 27),
    MESS_CAPSULE_EX98_DONKEY = MESSNUM(MESS_CAPSULE_EX98, 28),
    MESS_CAPSULE_EX98_VS = MESSNUM(MESS_CAPSULE_EX98, 29),
    MESS_CAPSULE_EX98_ERROR = MESSNUM(MESS_CAPSULE_EX98, 30),
    MESS_CAPSULE_EX98_EVENT = MESSNUM(MESS_CAPSULE_EX98, 31),
    MESS_CAPSULE_EX98_SAIHIDDEN = MESSNUM(MESS_CAPSULE_EX98, 32),
};

#endif