#ifndef MESSNUM_MESS_CAPSULE_EX01
#define MESSNUM_MESS_CAPSULE_EX01

#include "messdir_enum.h"

enum {
    MESS_CAPSULE_EX01_DOKAN_NULL = MESSNUM(MESS_CAPSULE_EX01, 0),
    MESS_CAPSULE_EX01_DOKAN_SWAP = MESSNUM(MESS_CAPSULE_EX01, 1),
    MESS_CAPSULE_EX01_DOKAN_SWAP_ROULETTE = MESSNUM(MESS_CAPSULE_EX01, 2),
    MESS_CAPSULE_EX01_JANGO_NULL = MESSNUM(MESS_CAPSULE_EX01, 3),
    MESS_CAPSULE_EX01_JANGO_SWAP = MESSNUM(MESS_CAPSULE_EX01, 4),
    MESS_CAPSULE_EX01_JANGO_SWAP_ROULETTE = MESSNUM(MESS_CAPSULE_EX01, 5),
    MESS_CAPSULE_EX01_BOBLE_END = MESSNUM(MESS_CAPSULE_EX01, 6),
    MESS_CAPSULE_EX01_HANACHAN_STAR = MESSNUM(MESS_CAPSULE_EX01, 7),
    MESS_CAPSULE_EX01_HANACHAN_STAR_GOTO = MESSNUM(MESS_CAPSULE_EX01, 8),
    MESS_CAPSULE_EX01_HANACHAN_STAR_CANCEL = MESSNUM(MESS_CAPSULE_EX01, 9),
    MESS_CAPSULE_EX01_HANACHAN_STAR_MAX = MESSNUM(MESS_CAPSULE_EX01, 10),
    MESS_CAPSULE_EX01_HANACHAN_COIN_LOW = MESSNUM(MESS_CAPSULE_EX01, 11),
};

#endif