#ifndef MESSNUM_MESS_CAPSULE_EX02
#define MESSNUM_MESS_CAPSULE_EX02

#include "messdir_enum.h"

enum {
    MESS_CAPSULE_EX02_HAMMERBRO_COIN = MESSNUM(MESS_CAPSULE_EX02, 0),
    MESS_CAPSULE_EX02_HAMMERBRO_COIN_NONE = MESSNUM(MESS_CAPSULE_EX02, 1),
    MESS_CAPSULE_EX02_COIN_BLOCK_START = MESSNUM(MESS_CAPSULE_EX02, 2),
    MESS_CAPSULE_EX02_TOGEZO_ROULETTE = MESSNUM(MESS_CAPSULE_EX02, 3),
    MESS_CAPSULE_EX02_TOGEZO = MESSNUM(MESS_CAPSULE_EX02, 4),
    MESS_CAPSULE_EX02_NULL = MESSNUM(MESS_CAPSULE_EX02, 5),
    MESS_CAPSULE_EX02_PATAPATA_COIN = MESSNUM(MESS_CAPSULE_EX02, 6),
    MESS_CAPSULE_EX02_PATAPATA_COIN_NONE = MESSNUM(MESS_CAPSULE_EX02, 7),
    MESS_CAPSULE_EX02_PATAPATA_RESULT = MESSNUM(MESS_CAPSULE_EX02, 8),
    MESS_CAPSULE_EX02_PATAPATA_COIN_TAKE = MESSNUM(MESS_CAPSULE_EX02, 9),
    MESS_CAPSULE_EX02_KILLER_NUM = MESSNUM(MESS_CAPSULE_EX02, 10),
    MESS_CAPSULE_EX02_KURIBO_ROULETTE = MESSNUM(MESS_CAPSULE_EX02, 11),
    MESS_CAPSULE_EX02_KURIBO = MESSNUM(MESS_CAPSULE_EX02, 12),
    MESS_CAPSULE_EX02_KURIBO_TEAM = MESSNUM(MESS_CAPSULE_EX02, 13),
    MESS_CAPSULE_EX02_KURIBO_SWAP = MESSNUM(MESS_CAPSULE_EX02, 14),
    MESS_CAPSULE_EX02_KURIBO_END = MESSNUM(MESS_CAPSULE_EX02, 15),
    MESS_CAPSULE_EX02_KURIBO_NOCOIN = MESSNUM(MESS_CAPSULE_EX02, 16),
    MESS_CAPSULE_EX02_BANK_COST = MESSNUM(MESS_CAPSULE_EX02, 17),
    MESS_CAPSULE_EX02_BANK_FAIL = MESSNUM(MESS_CAPSULE_EX02, 18),
    MESS_CAPSULE_EX02_BANK_COIN_NUM = MESSNUM(MESS_CAPSULE_EX02, 19),
    MESS_CAPSULE_EX02_BANK_GETALL = MESSNUM(MESS_CAPSULE_EX02, 20),
    MESS_CAPSULE_EX02_BANK_EMPTY = MESSNUM(MESS_CAPSULE_EX02, 21),
    MESS_CAPSULE_EX02_BANK_END = MESSNUM(MESS_CAPSULE_EX02, 22),
};

#endif