#ifndef MESSNUM_MESS_CAPSULE_EX03
#define MESSNUM_MESS_CAPSULE_EX03

#include "messdir_enum.h"

enum {
    MESS_CAPSULE_EX03_KAMEKKU_SWAP = MESSNUM(MESS_CAPSULE_EX03, 0),
    MESS_CAPSULE_EX03_KAMEKKU_FAIL = MESSNUM(MESS_CAPSULE_EX03, 1),
    MESS_CAPSULE_EX03_KAMEKKU_SHUFFLE = MESSNUM(MESS_CAPSULE_EX03, 2),
    MESS_CAPSULE_EX03_THROWMAN = MESSNUM(MESS_CAPSULE_EX03, 3),
    MESS_CAPSULE_EX03_THROWMAN_RESULT = MESSNUM(MESS_CAPSULE_EX03, 4),
    MESS_CAPSULE_EX03_THROWMAN_NULL = MESSNUM(MESS_CAPSULE_EX03, 5),
    MESS_CAPSULE_EX03_PAKKUN = MESSNUM(MESS_CAPSULE_EX03, 6),
    MESS_CAPSULE_EX03_PAKKUN_RESULT = MESSNUM(MESS_CAPSULE_EX03, 7),
    MESS_CAPSULE_EX03_PAKKUN_NULL = MESSNUM(MESS_CAPSULE_EX03, 8),
    MESS_CAPSULE_EX03_KOKAMEKKU_ROULETTE = MESSNUM(MESS_CAPSULE_EX03, 9),
    MESS_CAPSULE_EX03_KOKAMEKKU = MESSNUM(MESS_CAPSULE_EX03, 10),
    MESS_CAPSULE_EX03_KOKAMEKKU_TEAM = MESSNUM(MESS_CAPSULE_EX03, 11),
    MESS_CAPSULE_EX03_KOKAMEKKU_FAIL = MESSNUM(MESS_CAPSULE_EX03, 12),
    MESS_CAPSULE_EX03_KOKAMEKKU_END = MESSNUM(MESS_CAPSULE_EX03, 13),
    MESS_CAPSULE_EX03_UKKI_CHOICE = MESSNUM(MESS_CAPSULE_EX03, 14),
    MESS_CAPSULE_EX03_UKKI_START = MESSNUM(MESS_CAPSULE_EX03, 15),
    MESS_CAPSULE_EX03_UKKI_END = MESSNUM(MESS_CAPSULE_EX03, 16),
    MESS_CAPSULE_EX03_UKKI_RESULT = MESSNUM(MESS_CAPSULE_EX03, 17),
    MESS_CAPSULE_EX03_UKKI_HELP_FAIL = MESSNUM(MESS_CAPSULE_EX03, 18),
    MESS_CAPSULE_EX03_UKKI_FAIL = MESSNUM(MESS_CAPSULE_EX03, 19),
    MESS_CAPSULE_EX03_JUGEM_CHOICE = MESSNUM(MESS_CAPSULE_EX03, 20),
    MESS_CAPSULE_EX03_JUGEM_TEAM = MESSNUM(MESS_CAPSULE_EX03, 21),
    MESS_CAPSULE_EX03_JUGEM_END = MESSNUM(MESS_CAPSULE_EX03, 22),
    MESS_CAPSULE_EX03_JUGEM_CAPSULE = MESSNUM(MESS_CAPSULE_EX03, 23),
    MESS_CAPSULE_EX03_JUGEM_FAIL = MESSNUM(MESS_CAPSULE_EX03, 24),
    MESS_CAPSULE_EX03_JUGEM_INSSPACE = MESSNUM(MESS_CAPSULE_EX03, 25),
    MESS_CAPSULE_EX03_JUGEM_LUCK = MESSNUM(MESS_CAPSULE_EX03, 26),
    MESS_CAPSULE_EX03_JUGEM_CAPSULE_EMPTY = MESSNUM(MESS_CAPSULE_EX03, 27),
    MESS_CAPSULE_EX03_JUGEM_OTHER_TEAM = MESSNUM(MESS_CAPSULE_EX03, 28),
    MESS_CAPSULE_EX03_JUGEM_RESULT = MESSNUM(MESS_CAPSULE_EX03, 29),
};

#endif