#ifndef MESSNUM_CHARANAME_H
#define MESSNUM_CHARANAME_H

#include "messdir_enum.h"

enum {
    CHARANAME_MARIO = MESSNUM(MESS_CHARANAME, 0),
    CHARANAME_LUIGI = MESSNUM(MESS_CHARANAME, 1),
    CHARANAME_PEACH = MESSNUM(MESS_CHARANAME, 2),
    CHARANAME_YOSHI = MESSNUM(MESS_CHARANAME, 3),
    CHARANAME_WARIO = MESSNUM(MESS_CHARANAME, 4),
    CHARANAME_DAISY = MESSNUM(MESS_CHARANAME, 5),
    CHARANAME_WALUIGI = MESSNUM(MESS_CHARANAME, 6),
    CHARANAME_KINOPIO = MESSNUM(MESS_CHARANAME, 7),
    CHARANAME_TERESA = MESSNUM(MESS_CHARANAME, 8),
    CHARANAME_MINIKOOPA = MESSNUM(MESS_CHARANAME, 9),
    CHARANAME_MINIKOOPAR = MESSNUM(MESS_CHARANAME, 10),
    CHARANAME_MINIKOOPAG = MESSNUM(MESS_CHARANAME, 11),
    CHARANAME_MINIKOOPAB = MESSNUM(MESS_CHARANAME, 12),
};

#endif