#ifndef MESSNUM_MESS_CHARANAME_H
#define MESSNUM_MESS_CHARANAME_H

#include "messdir_enum.h"

enum {
    MESS_CHARANAME_MARIO = MESSNUM(MESS_CHARANAME, 0),
    MESS_CHARANAME_LUIGI = MESSNUM(MESS_CHARANAME, 1),
    MESS_CHARANAME_PEACH = MESSNUM(MESS_CHARANAME, 2),
    MESS_CHARANAME_YOSHI = MESSNUM(MESS_CHARANAME, 3),
    MESS_CHARANAME_WARIO = MESSNUM(MESS_CHARANAME, 4),
    MESS_CHARANAME_DAISY = MESSNUM(MESS_CHARANAME, 5),
    MESS_CHARANAME_WALUIGI = MESSNUM(MESS_CHARANAME, 6),
    MESS_CHARANAME_KINOPIO = MESSNUM(MESS_CHARANAME, 7),
    MESS_CHARANAME_TERESA = MESSNUM(MESS_CHARANAME, 8),
    MESS_CHARANAME_MINIKOOPA = MESSNUM(MESS_CHARANAME, 9),
    MESS_CHARANAME_MINIKOOPAR = MESSNUM(MESS_CHARANAME, 10),
    MESS_CHARANAME_MINIKOOPAG = MESSNUM(MESS_CHARANAME, 11),
    MESS_CHARANAME_MINIKOOPAB = MESSNUM(MESS_CHARANAME, 12),
};

#endif