#ifndef MESSNUM_MESS_CIRCUITEVENT
#define MESSNUM_MESS_CIRCUITEVENT

#include "messdir_enum.h"

enum {
    MESS_CIRCUITEVENT_KETTOU_START = MESSNUM(MESS_CIRCUITEVENT, 0),
    MESS_CIRCUITEVENT_KETTOU_RESULT = MESSNUM(MESS_CIRCUITEVENT, 1),
    MESS_CIRCUITEVENT_KETTOU_LOSER = MESSNUM(MESS_CIRCUITEVENT, 2),
    MESS_CIRCUITEVENT_KETTOU_TIE = MESSNUM(MESS_CIRCUITEVENT, 3),
    MESS_CIRCUITEVENT_KETTOU_FAIL = MESSNUM(MESS_CIRCUITEVENT, 4),
    MESS_CIRCUITEVENT_KOOPA_MG_START = MESSNUM(MESS_CIRCUITEVENT, 5),
    MESS_CIRCUITEVENT_KOOPA_MG = MESSNUM(MESS_CIRCUITEVENT, 6),
    MESS_CIRCUITEVENT_KOOPA_MG_ROULETTE = MESSNUM(MESS_CIRCUITEVENT, 7),
    MESS_CIRCUITEVENT_KOOPA_MG_RESULT = MESSNUM(MESS_CIRCUITEVENT, 8),
    MESS_CIRCUITEVENT_KOOPA_MG_TIE = MESSNUM(MESS_CIRCUITEVENT, 9),
    MESS_CIRCUITEVENT_KOOPA_MG_END = MESSNUM(MESS_CIRCUITEVENT, 10),
    MESS_CIRCUITEVENT_KOOPA_MG_CANCEL = MESSNUM(MESS_CIRCUITEVENT, 11),
};

#endif