#ifndef MESSNUM_MESS_KOOPAMASU
#define MESSNUM_MESS_KOOPAMASU

#include "messdir_enum.h"

enum {
    MESS_KOOPAMASU_START_PARTY = MESSNUM(MESS_KOOPAMASU, 0),
    MESS_KOOPAMASU_START_EVENT1 = MESSNUM(MESS_KOOPAMASU, 1),
    MESS_KOOPAMASU_START_EVENT2 = MESSNUM(MESS_KOOPAMASU, 2),
    MESS_KOOPAMASU_START_EVENT3 = MESSNUM(MESS_KOOPAMASU, 3),
    MESS_KOOPAMASU_START_EVENT4 = MESSNUM(MESS_KOOPAMASU, 4),
    MESS_KOOPAMASU_LOSEREFF1 = MESSNUM(MESS_KOOPAMASU, 5),
    MESS_KOOPAMASU_LOSEREFF2 = MESSNUM(MESS_KOOPAMASU, 6),
    MESS_KOOPAMASU_LOSEREFF3 = MESSNUM(MESS_KOOPAMASU, 7),
    MESS_KOOPAMASU_ROULETTE = MESSNUM(MESS_KOOPAMASU, 8),
    MESS_KOOPAMASU_RESULT = MESSNUM(MESS_KOOPAMASU, 9),
    MESS_KOOPAMASU_RESULT_NOCOIN = MESSNUM(MESS_KOOPAMASU, 10),
    MESS_KOOPAMASU_RESULT_NOCAPSULE = MESSNUM(MESS_KOOPAMASU, 11),
    MESS_KOOPAMASU_RESULT_NOLOSE = MESSNUM(MESS_KOOPAMASU, 12),
    MESS_KOOPAMASU_DONKEY_START = MESSNUM(MESS_KOOPAMASU, 13),
    MESS_KOOPAMASU_DONKEY_CANCEL = MESSNUM(MESS_KOOPAMASU, 14),
    MESS_KOOPAMASU_DONKEY_FAIL = MESSNUM(MESS_KOOPAMASU, 15),
    MESS_KOOPAMASU_END = MESSNUM(MESS_KOOPAMASU, 16),
    MESS_KOOPAMASU_STORYCOM_START = MESSNUM(MESS_KOOPAMASU, 17),
    MESS_KOOPAMASU_STORYCOM_STEAL = MESSNUM(MESS_KOOPAMASU, 18),
    MESS_KOOPAMASU_STORYCOM_PLAYHARD = MESSNUM(MESS_KOOPAMASU, 19),
    MESS_KOOPAMASU_STORYCOM_STEAL_FAIL = MESSNUM(MESS_KOOPAMASU, 20),
    MESS_KOOPAMASU_STORY_START = MESSNUM(MESS_KOOPAMASU, 21),
    MESS_KOOPAMASU_STORY_LOSE = MESSNUM(MESS_KOOPAMASU, 22),
    MESS_KOOPAMASU_STORY_END = MESSNUM(MESS_KOOPAMASU, 23),
};

#endif