#ifndef MESSNUM_MESS_KOOPAMASU
#define MESSNUM_MESS_KOOPAMASU

#include "messdir_enum.h"

enum {
    MESS_LAST5KOOPA_START_PARTY = MESSNUM(MESS_LAST5KOOPA, 0),
    MESS_LAST5KOOPA_RANK_1 = MESSNUM(MESS_LAST5KOOPA, 1),
    MESS_LAST5KOOPA_RANK_2 = MESSNUM(MESS_LAST5KOOPA, 2),
    MESS_LAST5KOOPA_RANK_3 = MESSNUM(MESS_LAST5KOOPA, 3),
    MESS_LAST5KOOPA_RANK_4 = MESSNUM(MESS_LAST5KOOPA, 4),
    MESS_LAST5KOOPA_RESULT_PREDICT = MESSNUM(MESS_LAST5KOOPA, 5),
    MESS_LAST5KOOPA_ROULETTE = MESSNUM(MESS_LAST5KOOPA, 6),
    MESS_LAST5KOOPA_ROULETTE_RESULT = MESSNUM(MESS_LAST5KOOPA, 7),
    MESS_LAST5KOOPA_RESULT = MESSNUM(MESS_LAST5KOOPA, 8),
    MESS_LAST5KOOPA_EFFECT_1 = MESSNUM(MESS_LAST5KOOPA, 9),
    MESS_LAST5KOOPA_EFFECT_2 = MESSNUM(MESS_LAST5KOOPA, 10),
    MESS_LAST5KOOPA_EFFECT_3 = MESSNUM(MESS_LAST5KOOPA, 11),
    MESS_LAST5KOOPA_EFFECT_4 = MESSNUM(MESS_LAST5KOOPA, 12),
    MESS_LAST5KOOPA_START_STORY = MESSNUM(MESS_LAST5KOOPA, 13),
    MESS_LAST5KOOPA_MINIK_MULTI = MESSNUM(MESS_LAST5KOOPA, 14),
    MESS_LAST5KOOPA_MINIK_SINGLE = MESSNUM(MESS_LAST5KOOPA, 15),
    MESS_LAST5KOOPA_KETTOU_2X = MESSNUM(MESS_LAST5KOOPA, 16),
    MESS_LAST5KOOPA_COINNUM = MESSNUM(MESS_LAST5KOOPA, 17),
};

#endif