#ifndef MESSNUM_MESS_MGINSTSYS_H
#define MESSNUM_MESS_MGINSTSYS_H

#include "messdir_enum.h"

enum {
    MESS_MGINSTSYS_BTN_START = MESSNUM(MESS_MGINSTSYS, 0),
    MESS_MGINSTSYS_BTN_PRACTICE = MESSNUM(MESS_MGINSTSYS, 1),
    MESS_MGINSTSYS_RULES_INST = MESSNUM(MESS_MGINSTSYS, 2),
    MESS_MGINSTSYS_CTRL1_INST = MESSNUM(MESS_MGINSTSYS, 3),
    MESS_MGINSTSYS_CTRL2_INST = MESSNUM(MESS_MGINSTSYS, 4),
    MESS_MGINSTSYS_ADVICE1_INST = MESSNUM(MESS_MGINSTSYS, 5),
    MESS_MGINSTSYS_ADVICE2_INST = MESSNUM(MESS_MGINSTSYS, 6),
    MESS_MGINSTSYS_CTRLALL_INST = MESSNUM(MESS_MGINSTSYS, 7),
    MESS_MGINSTSYS_ADVICEALL_INST = MESSNUM(MESS_MGINSTSYS, 8),
    MESS_MGINSTSYS_BTN_EXIT = MESSNUM(MESS_MGINSTSYS, 9),
    MESS_MGINSTSYS_MES_START = MESSNUM(MESS_MGINSTSYS, 10),
    MESS_MGINSTSYS_MES_FINISH = MESSNUM(MESS_MGINSTSYS, 11),
    MESS_MGINSTSYS_MES_WIN = MESSNUM(MESS_MGINSTSYS, 12),
    MESS_MGINSTSYS_MES_DRAW = MESSNUM(MESS_MGINSTSYS, 13),
    MESS_MGINSTSYS_MES_RECORD = MESSNUM(MESS_MGINSTSYS, 14),
};

#endif