#ifndef MESSNUM_MESS_MGINST_H
#define MESSNUM_MESS_MGINST_H

#include "messdir_enum.h"

#define MESS_MGINST_MG_MESS(mgId) \
    MESS_MGINST_M##mgId##_1, \
    MESS_MGINST_M##mgId##_2, \
    MESS_MGINST_M##mgId##_3, \
    MESS_MGINST_M##mgId##_4, \
    MESS_MGINST_M##mgId##_5

#define MESS_MGINST_DECA_MG_MESS(mgId) \
    MESS_MGINST_DECA_M##mgId##_1, \
    MESS_MGINST_DECA_M##mgId##_2, \
    MESS_MGINST_DECA_M##mgId##_3, \
    MESS_MGINST_DECA_M##mgId##_4, \
    MESS_MGINST_DECA_M##mgId##_5
    
enum {
    MESS_MGINST_DUMMY_MESS = MESSNUM(MESS_MGINST, 0)-1,
    MESS_MGINST_MG_MESS(501),
    MESS_MGINST_MG_MESS(502),
    MESS_MGINST_MG_MESS(503),
    MESS_MGINST_MG_MESS(504),
    MESS_MGINST_MG_MESS(505),
    MESS_MGINST_MG_MESS(506),
    MESS_MGINST_MG_MESS(507),
    MESS_MGINST_MG_MESS(508),
    MESS_MGINST_MG_MESS(509),
    MESS_MGINST_MG_MESS(510),
    MESS_MGINST_MG_MESS(511),
    MESS_MGINST_MG_MESS(512),
    MESS_MGINST_MG_MESS(513),
    MESS_MGINST_MG_MESS(514),
    MESS_MGINST_MG_MESS(515),
    MESS_MGINST_MG_MESS(516),
    MESS_MGINST_MG_MESS(524),
    MESS_MGINST_MG_MESS(563),
    MESS_MGINST_MG_MESS(564),
    MESS_MGINST_MG_MESS(565),
    MESS_MGINST_MG_MESS(566),
    MESS_MGINST_MG_MESS(576),
    MESS_MGINST_MG_MESS(579),
    MESS_MGINST_MG_MESS(517),
    MESS_MGINST_MG_MESS(518),
    MESS_MGINST_MG_MESS(519),
    MESS_MGINST_MG_MESS(520),
    MESS_MGINST_MG_MESS(522),
    MESS_MGINST_MG_MESS(523),
    MESS_MGINST_MG_MESS(525),
    MESS_MGINST_MG_MESS(567),
    MESS_MGINST_MG_MESS(568),
    MESS_MGINST_MG_MESS(569),
    MESS_MGINST_MG_MESS(570),
    MESS_MGINST_MG_MESS(577),
    MESS_MGINST_MG_MESS(521),
    MESS_MGINST_MG_MESS(526),
    MESS_MGINST_MG_MESS(527),
    MESS_MGINST_MG_MESS(528),
    MESS_MGINST_MG_MESS(529),
    MESS_MGINST_MG_MESS(530),
    MESS_MGINST_MG_MESS(531),
    MESS_MGINST_MG_MESS(532),
    MESS_MGINST_MG_MESS(533),
    MESS_MGINST_MG_MESS(534),
    MESS_MGINST_MG_MESS(574),
    MESS_MGINST_MG_MESS(575),
    MESS_MGINST_MG_MESS(535),
    MESS_MGINST_MG_MESS(536),
    MESS_MGINST_MG_MESS(537),
    MESS_MGINST_MG_MESS(538),
    MESS_MGINST_MG_MESS(539),
    MESS_MGINST_MG_MESS(540),
    MESS_MGINST_MG_MESS(541),
    MESS_MGINST_MG_MESS(542),
    MESS_MGINST_MG_MESS(543),
    MESS_MGINST_MG_MESS(544),
    MESS_MGINST_MG_MESS(545),
    MESS_MGINST_MG_MESS(546),
    MESS_MGINST_MG_MESS(547),
    MESS_MGINST_MG_MESS(548),
    MESS_MGINST_MG_MESS(549),
    MESS_MGINST_MG_MESS(550),
    MESS_MGINST_MG_MESS(551),
    MESS_MGINST_MG_MESS(552),
    MESS_MGINST_MG_MESS(553),
    MESS_MGINST_MG_MESS(554),
    MESS_MGINST_MG_MESS(555),
    MESS_MGINST_MG_MESS(559),
    MESS_MGINST_MG_MESS(560),
    MESS_MGINST_MG_MESS(561),
    MESS_MGINST_MG_MESS(562),
    MESS_MGINST_M562_CTRL2,
    MESS_MGINST_MG_MESS(571),
    MESS_MGINST_MG_MESS(572),
    MESS_MGINST_MG_MESS(573),
    MESS_MGINST_MG_MESS(578),
    MESS_MGINST_MG_MESS(580),
    MESS_MGINST_DECA_NONE,
    MESS_MGINST_DECA_MG_MESS(502),
    MESS_MGINST_DECA_MG_MESS(504),
    MESS_MGINST_DECA_MG_MESS(506),
    MESS_MGINST_DECA_MG_MESS(507),
    MESS_MGINST_DECA_MG_MESS(510),
    MESS_MGINST_DECA_MG_MESS(511),
    MESS_MGINST_DECA_MG_MESS(512),
    MESS_MGINST_DECA_MG_MESS(513),
    MESS_MGINST_DECA_MG_MESS(514),
    MESS_MGINST_DECA_MG_MESS(563),
};

#undef MESS_MGINST_MG_MESS
#undef MESS_MGINST_DECA_MG_MESS

#endif