#ifndef MESSNUM_MGINSTSYS_H
#define MESSNUM_MGINSTSYS_H

#include "messdir_enum.h"

enum {
    MGINSTSYS_BTN_START = MESSNUM(MESS_MGINSTSYS, 0),
    MGINSTSYS_BTN_PRACTICE = MESSNUM(MESS_MGINSTSYS, 1),
    MGINSTSYS_RULES_INST = MESSNUM(MESS_MGINSTSYS, 2),
    MGINSTSYS_CTRL1_INST = MESSNUM(MESS_MGINSTSYS, 3),
    MGINSTSYS_CTRL2_INST = MESSNUM(MESS_MGINSTSYS, 4),
    MGINSTSYS_ADVICE1_INST = MESSNUM(MESS_MGINSTSYS, 5),
    MGINSTSYS_ADVICE2_INST = MESSNUM(MESS_MGINSTSYS, 6),
    MGINSTSYS_CTRLALL_INST = MESSNUM(MESS_MGINSTSYS, 7),
    MGINSTSYS_ADVICEALL_INST = MESSNUM(MESS_MGINSTSYS, 8),
    MGINSTSYS_BTN_EXIT = MESSNUM(MESS_MGINSTSYS, 9),
    MGINSTSYS_MES_START = MESSNUM(MESS_MGINSTSYS, 10),
    MGINSTSYS_MES_FINISH = MESSNUM(MESS_MGINSTSYS, 11),
    MGINSTSYS_MES_WIN = MESSNUM(MESS_MGINSTSYS, 12),
    MGINSTSYS_MES_DRAW = MESSNUM(MESS_MGINSTSYS, 13),
    MGINSTSYS_MES_RECORD = MESSNUM(MESS_MGINSTSYS, 14),
};

#endif