#ifndef MESSNUM_MESS_MGMODE_SYS_H
#define MESSNUM_MESS_MGMODE_SYS_H

#include "messdir_enum.h"

enum {
    MESS_MGMODE_SYS_ENTER = MESSNUM(MESS_MGMODE_SYS, 0),
    MESS_MGMODE_SYS_QUIT,
    MESS_MGMODE_SYS_PLAYER_NUM_START,
    MESS_MGMODE_SYS_PLAYER_NUM,
    MESS_MGMODE_SYS_PLAYER_NUM_1,
    MESS_MGMODE_SYS_PLAYER_NUM_2,
    MESS_MGMODE_SYS_PLAYER_NUM_3,
    MESS_MGMODE_SYS_PLAYER_NUM_4,
    MESS_MGMODE_SYS_CHR_SEL_MAN,
    MESS_MGMODE_SYS_CHR_SEL_COM,
    MESS_MGMODE_SYS_DIF_SEL,
    MESS_MGMODE_SYS_CUT,
    MESS_MGMODE_SYS_MGFREE,
    MESS_MGMODE_SYS_MGMATCH,
    MESS_MGMODE_SYS_MGCIRCUIT,
    MESS_MGMODE_SYS_MGDECA,
    MESS_MGMODE_SYS_MGWARS,
    MESS_MGMODE_SYS_MGTOUR,
    MESS_MGMODE_SYS_CUT2,
    MESS_MGMODE_SYS_MGMATCH_MODE_3,
    MESS_MGMODE_SYS_MGMATCH_MODE_5,
    MESS_MGMODE_SYS_MGMATCH_MODE_7,
    MESS_MGMODE_SYS_GENRE_SEL,
    MESS_MGMODE_SYS_CONFIRM,
    MESS_MGMODE_SYS_RESET,
    MESS_MGMODE_SYS_MG_START,
    MESS_MGMODE_SYS_TEAM_SEL,
    
};

#endif