#ifndef MESSNUM_MESS_MPMODE_H
#define MESSNUM_MESS_MPMODE_H

#include "messdir_enum.h"

enum {
    MESS_MPMODE_ENTER = MESSNUM(MESS_MPMODE, 0),
    MESS_MPMODE_EXIT,
    MESS_MPMODE_MDPARTY,
    MESS_MPMODE_MDSTORY,
    MESS_MPMODE_MDMINI,
    MESS_MPMODE_MDOMAKE,
    MESS_MPMODE_SDROOM,
    MESS_MPMODE_MDOPTION,
    MESS_MPMODE_RETURN
};

#endif