#ifndef MESSNUM_MESS_STORYEVENT
#define MESSNUM_MESS_STORYEVENT

#include "messdir_enum.h"

enum {
    MESS_STORYEVENT_KETTOU_START = MESSNUM(MESS_STORYEVENT, 0),
    MESS_STORYEVENT_KETTOU_COIN = MESSNUM(MESS_STORYEVENT, 1),
    MESS_STORYEVENT_KETTOU_RESULT_WIN = MESSNUM(MESS_STORYEVENT, 2),
    MESS_STORYEVENT_KETTOU_RESULT_LOSE = MESSNUM(MESS_STORYEVENT, 3),
    MESS_STORYEVENT_KETTOU_RESULT_TIE = MESSNUM(MESS_STORYEVENT, 4),
};

#endif