#ifndef MESSNUM_MESS_SYSHELP_H
#define MESSNUM_MESS_SYSHELP_H

#include "messdir_enum.h"

enum {
    MESS_SYSHELP_FILESEL = MESSNUM(MESS_SYSHELP, 0),
    MESS_SYSHELP_FILESEL_COPY = MESSNUM(MESS_SYSHELP, 1),
    MESS_SYSHELP_FILESEL_NOCOPY = MESSNUM(MESS_SYSHELP, 2),
    MESS_SYSHELP_MENU_ENTER = MESSNUM(MESS_SYSHELP, 3),
    MESS_SYSHELP_MENU_SEL = MESSNUM(MESS_SYSHELP, 4),
    MESS_SYSHELP_MENU_CHANGE = MESSNUM(MESS_SYSHELP, 5),
    MESS_SYSHELP_HIT = MESSNUM(MESS_SYSHELP, 9),
    MESS_SYSHELP_CONTINUE = MESSNUM(MESS_SYSHELP, 10),
    MESS_SYSHELP_RETURN = MESSNUM(MESS_SYSHELP, 11),
    MESS_SYSHELP_PARTYRESULT = MESSNUM(MESS_SYSHELP, 12),
    MESS_SYSHELP_PARTYRESULT_END = MESSNUM(MESS_SYSHELP, 13),
    MESS_SYSHELP_MAPVIEW = MESSNUM(MESS_SYSHELP, 14),
    MESS_SYSHELP_SAI = MESSNUM(MESS_SYSHELP, 15),
    MESS_SYSHELP_ITEMSEL = MESSNUM(MESS_SYSHELP, 16),
    MESS_SYSHELP_ROULETTE_STOP = MESSNUM(MESS_SYSHELP, 17),
    MESS_SYSHELP_SELCONFIRM = MESSNUM(MESS_SYSHELP, 18),
    MESS_SYSHELP_SCROLL = MESSNUM(MESS_SYSHELP, 19),
    MESS_SYSHELP_MAPVIEW_PLAYER = MESSNUM(MESS_SYSHELP, 20),
    MESS_SYSHELP_PAUSE = MESSNUM(MESS_SYSHELP, 21),
    MESS_SYSHELP_YESNO = MESSNUM(MESS_SYSHELP, 22),
    MESS_SYSHELP_OPENINGHIT = MESSNUM(MESS_SYSHELP, 23),
    MESS_SYSHELP_SD_BUY = MESSNUM(MESS_SYSHELP, 24),
    MESS_SYSHELP_SD_CONFIRM = MESSNUM(MESS_SYSHELP, 25),
    MESS_SYSHELP_SD_PICTURE = MESSNUM(MESS_SYSHELP, 26),
    MESS_SYSHELP_SD_PICSELECT = MESSNUM(MESS_SYSHELP, 27),
    MESS_SYSHELP_SD_SWITCH = MESSNUM(MESS_SYSHELP, 28),
    MESS_SYSHELP_SEL_LRSCROLL = MESSNUM(MESS_SYSHELP, 29),
    MESS_SYSHELP_SEL_EXIT = MESSNUM(MESS_SYSHELP, 30),
    MESS_SYSHELP_OPTION_BOARDRECORD = MESSNUM(MESS_SYSHELP, 31),
    MESS_SYSHELP_OPTION_SNDSEL = MESSNUM(MESS_SYSHELP, 32),
    MESS_SYSHELP_OPTION_ENTER = MESSNUM(MESS_SYSHELP, 33),
    MESS_SYSHELP_OPTION_SELCONFIRM = MESSNUM(MESS_SYSHELP, 34),
    MESS_SYSHELP_OPTION_CONFIRM = MESSNUM(MESS_SYSHELP, 35),
    MESS_SYSHELP_OPTION_LIST = MESSNUM(MESS_SYSHELP, 36),
    MESS_SYSHELP_OPTION_MGLIST = MESSNUM(MESS_SYSHELP, 36),
};

#endif