#ifndef MESSNUM_MESS_VSMASU
#define MESSNUM_MESS_VSMASU

#include "messdir_enum.h"

enum {
    MESS_VSMASU_START_3P = MESSNUM(MESS_VSMASU, 0),
    MESS_VSMASU_START_2P = MESSNUM(MESS_VSMASU, 1),
    MESS_VSMASU_START_4P = MESSNUM(MESS_VSMASU, 2),
    MESS_VSMASU_RESULT_WIN_MULTI = MESSNUM(MESS_VSMASU, 3),
    MESS_VSMASU_RESULT_WIN = MESSNUM(MESS_VSMASU, 4),
    MESS_VSMASU_RESULT_LOSE = MESSNUM(MESS_VSMASU, 5),
    MESS_VSMASU_RESULT_LOSE_END = MESSNUM(MESS_VSMASU, 6),
    MESS_VSMASU_RESULT_TIE = MESSNUM(MESS_VSMASU, 7),
};

#endif