#ifndef DATANUM_BDEMO_H
#define DATANUM_BDEMO_H

#include "datadir_enum.h"

enum {
    BDEMO_HSF_koopa = DATANUM(DATA_bdemo, 6),
    BDEMO_HSF_koopaIdle = DATANUM(DATA_bdemo, 7),
    BDEMO_HSF_koopaWalk = DATANUM(DATA_bdemo, 8),
    BDEMO_HSF_koopaLaugh = DATANUM(DATA_bdemo, 9),
    BDEMO_HSF_koopaJumpStart = DATANUM(DATA_bdemo, 10),
    BDEMO_HSF_koopaJump = DATANUM(DATA_bdemo, 11),
    BDEMO_HSF_koopaFingerPoint = DATANUM(DATA_bdemo, 12),
    BDEMO_HSF_koopaTalk = DATANUM(DATA_bdemo, 13),
    BDEMO_HSF_koopaAngry = DATANUM(DATA_bdemo, 14),
    BDEMO_HSF_koopaAngryEnd = DATANUM(DATA_bdemo, 15),
    BDEMO_HSF_koopaWarn = DATANUM(DATA_bdemo, 16),
    BDEMO_HSF_koopaHandUp = DATANUM(DATA_bdemo, 17),
    BDEMO_HSF_koopaWin = DATANUM(DATA_bdemo, 18),
    BDEMO_HSF_koopaFireStart = DATANUM(DATA_bdemo, 19),
    BDEMO_HSF_koopaFlex = DATANUM(DATA_bdemo, 20),
    BDEMO_HSF_minikoopaIdle = DATANUM(DATA_bdemo, 21),
    BDEMO_HSF_minikoopaRun = DATANUM(DATA_bdemo, 22),
    BDEMO_HSF_minikoopaFistUp = DATANUM(DATA_bdemo, 23),
    BDEMO_HSF_minikoopaArmDown = DATANUM(DATA_bdemo, 24),
    BDEMO_HSF_minikoopaWarn = DATANUM(DATA_bdemo, 25),
    BDEMO_HSF_minikoopaPoint = DATANUM(DATA_bdemo, 26),
    BDEMO_HSF_minikoopaShake = DATANUM(DATA_bdemo, 27),
    BDEMO_HSF_minikoopaWalkShake = DATANUM(DATA_bdemo, 28),
    BDEMO_HSF_minikoopaLogoStartRed = DATANUM(DATA_bdemo, 29),
    BDEMO_HSF_minikoopaLogoStartGreen = DATANUM(DATA_bdemo, 30),
    BDEMO_HSF_minikoopaLogoStartBlue = DATANUM(DATA_bdemo, 31),
    BDEMO_HSF_minikoopaArmUp = DATANUM(DATA_bdemo, 32),
    BDEMO_HSF_minikoopaSalute = DATANUM(DATA_bdemo, 33),
    BDEMO_HSF_minikoopaWin = DATANUM(DATA_bdemo, 34),
    BDEMO_HSF_minikoopaLose = DATANUM(DATA_bdemo, 35),
    BDEMO_HSF_minikoopaSad = DATANUM(DATA_bdemo, 36),
    BDEMO_HSF_minikoopaLeanL = DATANUM(DATA_bdemo, 37),
    BDEMO_HSF_minikoopaScare = DATANUM(DATA_bdemo, 38),
    BDEMO_HSF_minikoopaStackIdle = DATANUM(DATA_bdemo, 39),
    BDEMO_HSF_minikoopaShuffleArmIn = DATANUM(DATA_bdemo, 40),
    BDEMO_HSF_minikoopaShuffleArmOut = DATANUM(DATA_bdemo, 41),
    BDEMO_HSF_minikoopaShuffleJump = DATANUM(DATA_bdemo, 42),
    BDEMO_HSF_minikoopaSplitStart = DATANUM(DATA_bdemo, 43),
    BDEMO_HSF_minikoopaSplitMissing = DATANUM(DATA_bdemo, 44),
    BDEMO_HSF_minikoopaSplitStun = DATANUM(DATA_bdemo, 45),
    BDEMO_HSF_minikoopaSplitPunchR = DATANUM(DATA_bdemo, 46),
    BDEMO_HSF_minikoopaSplitPunchL = DATANUM(DATA_bdemo, 47),
    BDEMO_HSF_minikoopaSplitHit = DATANUM(DATA_bdemo, 48),
    BDEMO_HSF_minikoopaIdlePunch = DATANUM(DATA_bdemo, 49),
    BDEMO_HSF_minikoopaLogoR = DATANUM(DATA_bdemo, 50),
    BDEMO_HSF_minikoopaLogoG = DATANUM(DATA_bdemo, 51),
    BDEMO_HSF_minikoopaLogoB = DATANUM(DATA_bdemo, 52),
    BDEMO_HSF_minikoopaInEff = DATANUM(DATA_bdemo, 53),
};

#endif