#ifndef DATANUM_BPAUSE_H
#define DATANUM_BPAUSE_H

#include "datadir_enum.h"

enum {
    BPAUSE_HSF_cont = DATANUM(DATA_bpause, 0),
    BPAUSE_HSF_mgInstOn = DATANUM(DATA_bpause, 1),
    BPAUSE_HSF_mgInstOff = DATANUM(DATA_bpause, 2),
    BPAUSE_HSF_mgComOn = DATANUM(DATA_bpause, 3),
    BPAUSE_HSF_mgComOff = DATANUM(DATA_bpause, 4),
    BPAUSE_HSF_mgPackAll = DATANUM(DATA_bpause, 5),
    BPAUSE_HSF_mgPackEasy = DATANUM(DATA_bpause, 6),
    BPAUSE_HSF_mgPackAction = DATANUM(DATA_bpause, 7),
    BPAUSE_HSF_mgPackSkill = DATANUM(DATA_bpause, 8),
    BPAUSE_HSF_mgPackGoofy = DATANUM(DATA_bpause, 9),
    BPAUSE_HSF_rumbleOn = DATANUM(DATA_bpause, 10),
    BPAUSE_HSF_rumbleOff = DATANUM(DATA_bpause, 11),
    BPAUSE_HSF_messSpeedFast = DATANUM(DATA_bpause, 12),
    BPAUSE_HSF_messSpeedMid = DATANUM(DATA_bpause, 13),
    BPAUSE_HSF_messSpeedSlow = DATANUM(DATA_bpause, 14),
    BPAUSE_HSF_saveAlways = DATANUM(DATA_bpause, 15),
    BPAUSE_HSF_saveOnce = DATANUM(DATA_bpause, 16),
    BPAUSE_HSF_saveNever = DATANUM(DATA_bpause, 17),
    BPAUSE_HSF_terl = DATANUM(DATA_bpause, 18),
    BPAUSE_HSF_gameModeCap = DATANUM(DATA_bpause, 19),
    BPAUSE_ANM_turnBack = DATANUM(DATA_bpause, 20),
    BPAUSE_ANM_contBack = DATANUM(DATA_bpause, 21),
    BPAUSE_ANM_turnNum = DATANUM(DATA_bpause, 22),
    BPAUSE_ANM_gameMode = DATANUM(DATA_bpause, 23),
    BPAUSE_ANM_saveMode = DATANUM(DATA_bpause, 24),
    BPAUSE_ANM_mgPack = DATANUM(DATA_bpause, 25),
    BPAUSE_ANM_quit = DATANUM(DATA_bpause, 26),
    BPAUSE_ANM_mgFlag = DATANUM(DATA_bpause, 27),
    BPAUSE_ANM_messSpeed = DATANUM(DATA_bpause, 28),
    BPAUSE_ANM_rumbleValue = DATANUM(DATA_bpause, 29),
    BPAUSE_ANM_quitLine = DATANUM(DATA_bpause, 30),
    BPAUSE_ANM_quitBack = DATANUM(DATA_bpause, 31),
    BPAUSE_ANM_cursor = DATANUM(DATA_bpause, 32),
    BPAUSE_ANM_cursorGlow = DATANUM(DATA_bpause, 33),
    BPAUSE_ANM_playerNum = DATANUM(DATA_bpause, 34),
    BPAUSE_ANM_comDif = DATANUM(DATA_bpause, 35),
    BPAUSE_ANM_winFrame = DATANUM(DATA_bpause, 36),
    BPAUSE_ANM_winFrameBack = DATANUM(DATA_bpause, 37),
    BPAUSE_ANM_winCursor = DATANUM(DATA_bpause, 38),
    BPAUSE_ANM_contOption = DATANUM(DATA_bpause, 39),
    BPAUSE_ANM_contChar = DATANUM(DATA_bpause, 40),
    BPAUSE_HSF_contTouei = DATANUM(DATA_bpause, 41),
    BPAUSE_HSF_contCapsule = DATANUM(DATA_bpause, 42),
    BPAUSE_ANM_batsu = DATANUM(DATA_bpause, 43),
};

#endif