#ifndef DATANUM_DECATHLON_H
#define DATANUM_DECATHLON_H

#include "datadir_enum.h"

enum {
    DECATHLON_HSF_nerl = DATANUM(DATA_decathlon, 0),
    DECATHLON_HSF_nerl_idle,
    DECATHLON_HSF_hata,
    DECATHLON_HSF_stage,
    DECATHLON_HSF_crowd,
    DECATHLON_HSF_stage_night,
    DECATHLON_HSF_stage_fb,
    DECATHLON_HSF_kikyuu,
    DECATHLON_HSF_fuusen,
    DECATHLON_HSF_hikari,
    DECATHLON_HSF_moon,
    DECATHLON_HSF_light,
    DECATHLON_HSF_hanabi,
    DECATHLON_HSF_cover,
    DECATHLON_HSF_camera_focus,
    DECATHLON_HSF_camera_init,
    DECATHLON_HSF_camera_mg1,
    DECATHLON_HSF_camera_mg2,
    DECATHLON_HSF_camera_mg3,
    DECATHLON_HSF_camera_mg4,
    DECATHLON_HSF_camera_mg5,
    DECATHLON_HSF_camera_mg6,
    DECATHLON_HSF_camera_mg7,
    DECATHLON_HSF_camera_mg8,
    DECATHLON_HSF_camera_mg9,
    DECATHLON_HSF_camera_end_start,
    DECATHLON_HSF_camera_end_exit,
    DECATHLON_HSF_camera_alt,
    DECATHLON_HSF_main_light,
    DECATHLON_ANM_icon_m502,
    DECATHLON_ANM_icon_m504,
    DECATHLON_ANM_icon_m506,
    DECATHLON_ANM_icon_m507,
    DECATHLON_ANM_icon_m510,
    DECATHLON_ANM_icon_m511,
    DECATHLON_ANM_icon_m512,
    DECATHLON_ANM_icon_m513,
    DECATHLON_ANM_icon_m514,
    DECATHLON_ANM_icon_m563,
    DECATHLON_ANM_char_mario,
    DECATHLON_ANM_char_luigi,
    DECATHLON_ANM_char_peach,
    DECATHLON_ANM_char_yoshi,
    DECATHLON_ANM_char_wario,
    DECATHLON_ANM_char_daisy,
    DECATHLON_ANM_char_waluigi,
    DECATHLON_ANM_char_kinopio,
    DECATHLON_ANM_char_teresa,
    DECATHLON_ANM_char_minikoopa,
    DECATHLON_ANM_arrow
};

#endif