#ifndef DATANUM_MGCONST_H
#define DATANUM_MGCONST_H

#include "datadir_enum.h"

enum {
    MGCONST_ANM_mario = DATANUM(DATA_mgconst, 0),
    MGCONST_ANM_luigi = DATANUM(DATA_mgconst, 1),
    MGCONST_ANM_peach = DATANUM(DATA_mgconst, 2),
    MGCONST_ANM_yoshi = DATANUM(DATA_mgconst, 3),
    MGCONST_ANM_wario = DATANUM(DATA_mgconst, 4),
    MGCONST_ANM_donkey = DATANUM(DATA_mgconst, 5),
    MGCONST_ANM_daisy = DATANUM(DATA_mgconst, 6),
    MGCONST_ANM_waluigi = DATANUM(DATA_mgconst, 7),
    MGCONST_ANM_kinopio = DATANUM(DATA_mgconst, 8),
    MGCONST_ANM_teresa = DATANUM(DATA_mgconst, 9),
    MGCONST_ANM_minikoopa = DATANUM(DATA_mgconst, 10),
    MGCONST_ANM_minikoopaR = DATANUM(DATA_mgconst, 11),
    MGCONST_ANM_minikoopaG = DATANUM(DATA_mgconst, 12),
    MGCONST_ANM_minikoopaB = DATANUM(DATA_mgconst, 13),
    MGCONST_ANM_marioOutline = DATANUM(DATA_mgconst, 14),
    MGCONST_ANM_luigiOutline = DATANUM(DATA_mgconst, 15),
    MGCONST_ANM_peachOutline = DATANUM(DATA_mgconst, 16),
    MGCONST_ANM_yoshiOutline = DATANUM(DATA_mgconst, 17),
    MGCONST_ANM_warioOutline = DATANUM(DATA_mgconst, 18),
    MGCONST_ANM_donkeyOutline = DATANUM(DATA_mgconst, 19),
    MGCONST_ANM_daisyOutline = DATANUM(DATA_mgconst, 20),
    MGCONST_ANM_waluigiOutline = DATANUM(DATA_mgconst, 21),
    MGCONST_ANM_kinopioOutline = DATANUM(DATA_mgconst, 22),
    MGCONST_ANM_teresaOutline = DATANUM(DATA_mgconst, 23),
    MGCONST_ANM_minikoopaOutline = DATANUM(DATA_mgconst, 24),
    MGCONST_ANM_minikoopaROutline = DATANUM(DATA_mgconst, 25),
    MGCONST_ANM_minikoopaGOutline = DATANUM(DATA_mgconst, 26),
    MGCONST_ANM_minikoopaBOutline = DATANUM(DATA_mgconst, 27),
    MGCONST_ANM_coin = DATANUM(DATA_mgconst, 28),
    MGCONST_ANM_bomhei = DATANUM(DATA_mgconst, 29),
    MGCONST_ANM_star = DATANUM(DATA_mgconst, 30),
    MGCONST_ANM_starOn = DATANUM(DATA_mgconst, 31),
    MGCONST_ANM_marioSmall = DATANUM(DATA_mgconst, 32),
    MGCONST_ANM_luigiSmall = DATANUM(DATA_mgconst, 33),
    MGCONST_ANM_peachSmall = DATANUM(DATA_mgconst, 34),
    MGCONST_ANM_yoshiSmall = DATANUM(DATA_mgconst, 35),
    MGCONST_ANM_warioSmall = DATANUM(DATA_mgconst, 36),
    MGCONST_ANM_donkeySmall = DATANUM(DATA_mgconst, 37),
    MGCONST_ANM_daisySmall = DATANUM(DATA_mgconst, 38),
    MGCONST_ANM_waluigiSmall = DATANUM(DATA_mgconst, 39),
    MGCONST_ANM_kinopioSmall = DATANUM(DATA_mgconst, 40),
    MGCONST_ANM_teresaSmall = DATANUM(DATA_mgconst, 41),
    MGCONST_ANM_minikoopaSmall = DATANUM(DATA_mgconst, 42),
    MGCONST_ANM_minikoopaRSmall = DATANUM(DATA_mgconst, 43),
    MGCONST_ANM_minikoopaGSmall = DATANUM(DATA_mgconst, 44),
    MGCONST_ANM_minikoopaBSmall = DATANUM(DATA_mgconst, 45),
    MGCONST_ANM_scoreWin = DATANUM(DATA_mgconst, 46),
    MGCONST_ANM_scoreWinMask = DATANUM(DATA_mgconst, 47),
    MGCONST_ANM_scoreSmall = DATANUM(DATA_mgconst, 48),
    MGCONST_ANM_scoreMedium = DATANUM(DATA_mgconst, 49),
    MGCONST_ANM_scoreBlue = DATANUM(DATA_mgconst, 50),
    MGCONST_ANM_scoreLarge = DATANUM(DATA_mgconst, 51),
    MGCONST_ANM_scoreSegment = DATANUM(DATA_mgconst, 52),
    MGCONST_ANM_unitSmall = DATANUM(DATA_mgconst, 53),
    MGCONST_ANM_unitBlueSmall = DATANUM(DATA_mgconst, 54),
    MGCONST_ANM_unitBlueMedium = DATANUM(DATA_mgconst, 55),
    MGCONST_ANM_unitLarge = DATANUM(DATA_mgconst, 56),
    MGCONST_ANM_unitBlueLarge = DATANUM(DATA_mgconst, 57),
    MGCONST_ANM_scoreWinSmall = DATANUM(DATA_mgconst, 58),
    MGCONST_ANM_scoreRed = DATANUM(DATA_mgconst, 59),
    MGCONST_ANM_scoreChange = DATANUM(DATA_mgconst, 60),
    MGCONST_ANM_scoreYellow = DATANUM(DATA_mgconst, 61),
    MGCONST_ANM_scoreTimeGreen = DATANUM(DATA_mgconst, 62),
    MGCONST_ANM_scoreTime = DATANUM(DATA_mgconst, 63),
    MGCONST_ANM_scoreTimeBlue = DATANUM(DATA_mgconst, 64),
    MGCONST_ANM_scoreYellowSmall = DATANUM(DATA_mgconst, 65),
    MGCONST_ANM_scoreRecord = DATANUM(DATA_mgconst, 66),
    MGCONST_ANM_recordNew = DATANUM(DATA_mgconst, 67),
    MGCONST_ANM_recordCrown = DATANUM(DATA_mgconst, 68),
    MGCONST_ANM_crown = DATANUM(DATA_mgconst, 69),
    MGCONST_ANM_scoreCross = DATANUM(DATA_mgconst, 70),
    MGCONST_ANM_handMario = DATANUM(DATA_mgconst, 71),
    MGCONST_ANM_handLuigi = DATANUM(DATA_mgconst, 72),
    MGCONST_ANM_handPeach = DATANUM(DATA_mgconst, 73),
    MGCONST_ANM_handYoshi = DATANUM(DATA_mgconst, 74),
    MGCONST_ANM_handWario = DATANUM(DATA_mgconst, 75),
    MGCONST_ANM_handDonkey = DATANUM(DATA_mgconst, 76),
    MGCONST_ANM_handDaisy = DATANUM(DATA_mgconst, 77),
    MGCONST_ANM_handWaluigi = DATANUM(DATA_mgconst, 78),
};

#endif